### ISSUE TITLE
DAP-04 chores

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#404]
DAP-04 will need some routine changes:

- [x] Update version tags for HPKE to `"dap-04"` (#424)
- [x] Bump VDAF-03 to 05 (#429)
- [x] Update change log (#430)
- [x] Run spell check (#431)
